# Workflow name
name: PR Test

# Event for the workflow
on: 
  pull_request:
    branches:
      - main
    paths: ["src/components/**", "src/templates/**", "src/pages/**", "src/mocks/**"]

# List of jobs
jobs:
  test-and-push-results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          yarn install 
      - name: Test
        run: |
          yarn test
  